# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf7d38c2346e3a80dcb164fe9b65136f672b46cc3a1905e18aa884ca4f1f6e1e029eea089db68ee828feded765241093b6577a863e976d4515eee609a5dc614

test:
  secret_key_base: 43a3bc66d476c554ed1b0b59a16e95ce8281e84677c78a42da619e640122a1e96c32b9242d0d3d734d60c2b64e325b91f874bdf3136a2150e2b7926d11ece113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
